### ISSUE TITLE
AttributeError: 'VAEXperiment' object has no attribute '_lazy_train_dataloader'

### ISSUE THREAD

**Issue by Jia-Bin** [AntixK/PyTorch-VAE#10]
command: python run.py --config configs/vae.yaml
Then error messages pop up as the following:

INFO:root:gpu available: True, used: True
INFO:root:VISIBLE GPUS: 0
======= Training VanillaVAE =======
3099it [00:00, 8467848.92it/s]
Using downloaded and verified file: ../../shared/Data/celeba/list_attr_celeba.txt
Using downloaded and verified file: ../../shared/Data/celeba/identity_CelebA.txt
Using downloaded and verified file: ../../shared/Data/celeba/list_bbox_celeba.txt
Using downloaded and verified file: ../../shared/Data/celeba/list_landmarks_align_celeba.txt
Using downloaded and verified file: ../../shared/Data/celeba/list_eval_partition.txt
3099it [00:00, 6145696.50it/s]
Using downloaded and verified file: ../../shared/Data/celeba/list_attr_celeba.txt
Using downloaded and verified file: ../../shared/Data/celeba/identity_CelebA.txt
Using downloaded and verified file: ../../shared/Data/celeba/list_bbox_celeba.txt
Using downloaded and verified file: ../../shared/Data/celeba/list_landmarks_align_celeba.txt
Using downloaded and verified file: ../../shared/Data/celeba/list_eval_partition.txt
Traceback (most recent call last):
  File "/home/jbhuang/anaconda3/envs/vae2/lib/python3.7/site-packages/pytorch_lightning/core/decorators.py", line 17, in _get_data_loader
    value = getattr(self, attr_name)
  File "/home/jbhuang/anaconda3/envs/vae2/lib/python3.7/site-packages/torch/nn/modules/module.py", line 591, in __getattr__
    type(self).__name__, name))
AttributeError: 'VAEXperiment' object has no attribute '_lazy_train_dataloader'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jbhuang/MyWork/vae/PyTorch-VAE/utils.py", line 17, in func_wrapper
    return pl.data_loader(fn)(self)
  File "/home/jbhuang/anaconda3/envs/vae2/lib/python3.7/site-packages/pytorch_lightning/core/decorators.py", line 20, in _get_data_loader
    value = fn(self)  # Lazy evaluation, done only once.
  File "/home/jbhuang/MyWork/vae/PyTorch-VAE/experiment.py", line 143, in train_dataloader
    download=True) #Bill
  File "/home/jbhuang/anaconda3/envs/vae2/lib/python3.7/site-packages/torchvision/datasets/celeba.py", line 63, in __init__
    self.download()
  File "/home/jbhuang/anaconda3/envs/vae2/lib/python3.7/site-packages/torchvision/datasets/celeba.py", line 117, in download
    with zipfile.ZipFile(os.path.join(self.root, self.base_folder, "img_align_celeba.zip"), "r") as f:
  File "/home/jbhuang/anaconda3/envs/vae2/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/home/jbhuang/anaconda3/envs/vae2/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

Please help, thank you.

**Comment by ksachdeva** [comment]
I had seen this happening a few days back when in experiment.py I set download=True

The zip file downloaded by the library (that this project uses) is indeed invalid. 

What worked for me was -

a) Go to https://drive.google.com/drive/folders/0B7EVK8r0v71pWEZsZE9oNnFzTm8
b) Go to "img" directory at the above link and download img_align_celeba.zip
c) Go to "Anno" directory at the above link and download all .txt files
d) Go to "Eval" directory at the above link and download the txt file in it

Place all these files (.zip and .txt) at ../../shared/Data/celeba. This path is relative to where you cloned this repo. You should delete the existing files and replace them with the ones I have provided link to.

Hope this helps.

**Comment by Jia-Bin** [comment]
> I had seen this happening a few days back when in experiment.py I set download=True
> 
> The zip file downloaded by the library (that this project uses) is indeed invalid.
> 
> What worked for me was -
> 
> a) Go to https://drive.google.com/drive/folders/0B7EVK8r0v71pWEZsZE9oNnFzTm8
> b) Go to "img" directory at the above link and download img_align_celeba.zip
> c) Go to "Anno" directory at the above link and download all .txt files
> d) Go to "Eval" directory at the above link and download the txt file in it
> 
> Place all these files (.zip and .txt) at ../../shared/Data/celeba. This path is relative to where you cloned this repo. You should delete the existing files and replace them with the ones I have provided link to.
> 
> Hope this helps.

Hi Kapil:
Thank you so much. 
It works now!
