### ISSUE TITLE
Why not use rsample() PyTorch

### ISSUE THREAD

**Issue by btilmon** [AntixK/PyTorch-VAE#13]
Is there a reason for manually implementing reparameterization instead of using the rsample method provided in PyTorch?

**Comment by botkevin** [comment]
I'm pretty sure they are equivalent, it's just the original paper details this reparameterization trick https://arxiv.org/abs/1312.6114. IIRC rsample takes the variance (std^2), but that's not a big deal.

**Comment by AntixK** [comment]
Closing as the answer is given by @botkevin
