### ISSUE TITLE
Issues with newest version of Lightning (0.7.0 & 0.7.1)

### ISSUE THREAD

**Issue by BradWyble** [AntixK/PyTorch-VAE#2]
I've been running into this error when using your package when running on the newest master version of lightning.  Running this command:

python run.py -c configs/cvae.yaml 

results in ultimate error message:  
AttributeError: 'VAEXperiment' object has no attribute 'num_train_imgs'

This is with Python 3.7. 

When I downgrade to Lightning version 0.6.0 the same command works.

**Comment by BradWyble** [comment]
Working through this, it seems that in version 0.7.1 of lightning, there is no longer a call to traindataloader() prior to doing validation.

**Comment by BradWyble** [comment]
Was able to fix this by adding modifying validationloader as follows:

    def val_dataloader(self):
        transform = self.data_transforms()

        if self.params['dataset'] == 'celeba':
            self.sample_dataloader =  DataLoader(CelebA(root = self.params['data_path'],
                                                        split = "test",
                                                        transform=transform,
                                                        download=False),
                                                 batch_size= 144,
                                                 shuffle = True,
                                                 drop_last=True)
            valset =  CelebA(root = self.params['data_path'],
                                                        split = "test",
                                                        transform=transform,
                                                        download=False)



        else:
            raise ValueError('Undefined dataset type')
        self.num_val_imgs = len(valset)
        return self.sample_dataloader


And then modifying validation_step as follows:

def validation_step(self, batch, batch_idx, optimizer_idx = 0):
        real_img, labels = batch
        self.curr_device = real_img.device

        results = self.forward(real_img, labels = labels)
        val_loss = self.model.loss_function(*results,
                                            M_N = self.params['batch_size']/ self.num_val_imgs,
                                            optimizer_idx = optimizer_idx,
                                            batch_idx = batch_idx)

        return val_loss

**Comment by AntixK** [comment]
Good catch! Thanks for the correction. I have added a quick fix for 0.6 and 0.7 version (as you have done) and handling for future deprecation of the decorators from version 0.9. Refer this commit 90172be3a00b1d76a6b3741c6fdb5b5f52ccbe4d
