### ISSUE TITLE
LibTorch VAE Implementation

### ISSUE THREAD

**Issue by pranav-vempati** [AntixK/PyTorch-VAE#24]
Thank you for sharing your comprehensive and illuminating set of examples in this repository. I'm currently thinking of re-implementing a subset of these models, based on your Python implementations, using LibTorch, PyTorch's C++ frontend. 
Providing I obtain some fruitful results, would you be interested in hosting some of those models here?

**Comment by AntixK** [comment]
Sounds great. I you would submit a PR, I will check it out and merge it
