### ISSUE TITLE
lightning 0.7.2

### ISSUE THREAD

**Issue by williamFalcon** [AntixK/PyTorch-VAE#3]
hey! really cool repo. Just wanted to let you know you should upgrade to 0.7.2 as it includes a good amount of additional functionality including TPU training and solves a good deal of bugs for edge cases. 

in addition, it makes the code MUCH simpler and adds a few more training loop hooks

**Comment by threewisemonkeys-as** [comment]
@AntixK  any plans to update to lightning >= 1.0? There seem to have been significant changes to the API

**Comment by GloryyrolG** [comment]
@williamFalcon So can the code directly run in pytorch-lightning >= 0.7.2? Thanks.

**Comment by AntixK** [comment]
Fixed in #46
