### ISSUE TITLE
Update to Latest Pytorch_Lightning

### ISSUE THREAD

**Issue by RyannDaGreat** [AntixK/PyTorch-VAE#30]
When I try to run this code, I get many errors that seem to be related to using deprecated options in pytorch_lightning, such as the max_nb_epochs option or the pytorch_lightning.logging module (which was replaced with the pytorch_lightning.logger module).
https://github.com/PyTorchLightning/pytorch-lightning/issues/663

Will this repo be updated to use the latest version of pytorch_lightning? I'm having a difficult time getting things to work

Thank you,
Ryan

**Comment by abcde441** [comment]
Using pytorch_lightning 0.60 should be ok.

**Comment by AntixK** [comment]
fixed in #46
