### ISSUE TITLE
Why is img_size default to 64?

### ISSUE THREAD

**Issue by toekneechin777** [AntixK/PyTorch-VAE#37]
Hi was wondering why the img_size parameter for experiments is set to 64 as the celebA dataset images are of much larger size.

I am trying to experiment this on a different dataset that is larger than celebA (512 x 512) and was wondering if I should change img_size to create better reconstructed images. I tried changing it myself but I ran into size mismatch issues even though I don't see in the model file where the size of 64 comes to play.

Any help would be much appreciated

**Comment by AntixK** [comment]
I just chose 64x64 for a quick standard implementation. It also takes fewer epochs to get good results. You can always create a larger network size. I hope you two resolved it among yourselves. Please re-open this issue if you need any further help.
