### ISSUE TITLE
CIFAR-10 results not good

### ISSUE THREAD

**Issue by PatrickBue** [AntixK/PyTorch-VAE#38]
I am trying to reproduce published results on the CIFAR-10 dataset. My results currently do not look good using the default parameters for e.g. Vanilla VAE (and others). I.e. the model learns something very blurry, similar to e.g. https://bjlkeng.github.io/images/m2_images.png

Any suggestions how to improve these, e.g. I noticed that reducing the weight of the KL-loss already makes a big difference.

**Comment by AntixK** [comment]
For CIFAR10, you can play around with the network architecture, KL weight (as you have done), and optimizer params. There are ample repos available that give better results on CIFAR10. This repo is meant as a quick reference.

**Comment by working12** [comment]
@PatrickBue How did you solve this? Can you share your solution kindly?
