### ISSUE TITLE
Dynamic Range in MS-SSIM-Loss

### ISSUE THREAD

**Issue by tobias-haenel** [AntixK/PyTorch-VAE#39]
Why do you compute the dynamic range in the MS-SSIM VAE from the data range of the reconstructed images. If I understand the original SSIM paper correctly, the dynamic range should be the largest values that the images might assume (e.g. 1.0)?

**Comment by AntixK** [comment]
DR does not mean the ratio between the maximum and minimum possible values of a given image (in that case, it would be akin to the bit depth). DR is just the ratio between the max and min pixel values. This, in the case of VAEs, depend upon the activation used. If sigmoid is used, the DR is indeed 1.0. However, if activation used is tanh, then DR is 2.0 (1.0 - (-1.0)).

**Comment by tobias-haenel** [comment]
But in the following line (234 of msssim_vae.py)
`img_range = img1.max() - img1.min()`
You do compute the image pixel value range of the reconstruction batch and not the dynamic range.

**Comment by AntixK** [comment]
Nice catch. I agree that the `img_range` can be set to 1 by default or can be given as an additional parameter to the ` MSSIM` class.

**Comment by AntixK** [comment]
Fixed in #46
