### ISSUE TITLE
Dataset CIFAR-10

### ISSUE THREAD

**Issue by josianerodrigues** [AntixK/PyTorch-VAE#4]
Hi @AntixK,
Thank you for sharing your project with us.
I have a doubt. How do I use another dataset? I would like to use the CIFAR-10 collection. I changed the experiments file, but give the following error:

`  File "/home/josi/doutorado-2019/PyTorch-VAE/experiment.py", line 143, in train_dataloader
    download=True)
TypeError: __init__() got an unexpected keyword argument 'split'
`

Could you help me?

**Comment by AntixK** [comment]
Sorry for the late reply. CIFAR10 does not have the `split` argument (https://pytorch.org/docs/stable/torchvision/datasets.html#torchvision.datasets.CIFAR10); rather it has `train`. So, change it to `train=True` in the `train_dataloader` function and `train=False` in the `val_dataloader` function in `esperiment.py`.
