### ISSUE TITLE
Beta VAE: Strange input & output channels

### ISSUE THREAD

**Issue by ZechCal** [AntixK/PyTorch-VAE#43]
![image](https://user-images.githubusercontent.com/11711492/141665259-2de4c1eb-5803-4b19-839a-cff7ecdcf96d.png)
Why use hidden_dims[-1]*4?  This will cause a mismatch between the input channel and the output channel like this (If i got it right)
![image](https://user-images.githubusercontent.com/11711492/141665341-2acfaf20-9467-4301-86e7-80a3a5e213a7.png)
Thank you!

**Comment by ggao22** [comment]
Hi, I am also experiencing the same issue. How did you solve it?

**Comment by ZechCal** [comment]
I think it’s an issue with the size of the input data.

**Comment by vcasellesb** [comment]
> I think it’s an issue with the size of the input data.

Hi! I am a medical image segmentation student trying to understand VAEs.

I was looking at the VanillaVAE class, was confused by the [same lines as you](https://github.com/AntixK/PyTorch-VAE/blob/a6896b944c918dd7030e7d795a8c13e5c6345ec7/models/vanilla_vae.py#L36), and came across this thread.

I have a theory on why it's like that, and wanted to share my logic, maybe you can tell me if you agree with it.

The input dimensions are N x C (3) x 64 x 64. The encoder has 5 resolution stages, each of which halves image dimensions and doubles the number of channels from the starting number (32). Therefore, the spatial dimensions of the encoder outputs are N x [512](https://github.com/AntixK/PyTorch-VAE/blob/a6896b944c918dd7030e7d795a8c13e5c6345ec7/models/vanilla_vae.py#L22) x (64/(2^5)) x (64/2^5)) = N x 512 x 2 x 2.

The 4s we see in "hidden_dims[-1]*4" are what is needed to match the dimensions of the flattening of the encoder outputs (from N x 512 x 2 x 2 to N x 2048). Notice that hidden_dims[-1] is 512 and 4 is 2 * 2.

As you said @ZechCal, it is the result of the hard-coding of the input size throughout the model definition.

**Comment by ZechCal** [comment]
@vcasellesb This makes the problem more clear than ever, thanks for your insightful comments.
