### ISSUE TITLE
running program on macOS

### ISSUE THREAD

**Issue by ForeverAT** [AntixK/PyTorch-VAE#6]
Hi, I am a new programmer on Python and still new on writing program on computer. So it is a bit messy on how to manage the folder and package. While I am running the code, I have face the following error.
pytorch_lightning.utilities.debugging.MisconfigurationException: 
            You requested GPUs: [0]
            But your machine only has: []
May I ask is there any method to solve it. Thanks a lot

**Comment by AntixK** [comment]
I believe your machine does not have a CUDA enabled GPU. Try running the code on CPU. (Note: It will take very long time to run on the CPU).

Alternatively, if you wish to run the models, try using Google Colab. (Copy paste the code in Colab notebook) They offer a free GPU to train your model. Hope this helps!

**Comment by ForeverAT** [comment]
May I ask how can I adjust the code to run it on CPU? Thanks a lot

**Comment by ksachdeva** [comment]
To run the code on CPU, go to the respective config file e..g vae.yaml and in the `trainer_params` section set `gpus` to 0. 

That said, given the dataset, you would not be able to really train it using CPU as the author mentioned above.

 I do understand that it is helpful to run/debug/verify/understand the code on CPU before triggering the training on GPU.
