### ISSUE TITLE
Sampling in the Vamp VAE model

### ISSUE THREAD

**Issue by QipengGuo** [AntixK/PyTorch-VAE#9]
Hi, I have a question about the sampling process in the Vamp VAE model. [code](https://github.com/AntixK/PyTorch-VAE/blob/master/models/vampvae.py#L170)
I am new to VAE, so maybe my question is naive. And my question is why the code draws samples from the standard gaussian instead of the vamp prior?

**Comment by AntixK** [comment]
Hi,

Actually, the Vamp VAE implementation is incorrect. That is why I have referred to it under the contributions sections in the readme and not in the results section.

You are welcome to submit a PR if you implement one!
